FROM oven/bun:1 AS build
WORKDIR /app

COPY package.json bun.lock bunfig.toml ./
COPY client/package.json client/bunfig.toml ./client/
COPY server/package.json server/bunfig.toml ./server/

COPY tsconfig.json ./
COPY client/ ./client
COPY server/ ./server

WORKDIR /app/client
