services:
    server:
        build:
            args:
                BUILD_ENV: development
        volumes:
            - ./server/src:/app/server/src:ro
            - ./server/prisma:/app/server/prisma:ro
            - ./node_modules:/app/node_modules:ro
            - ./server/node_modules:/app/server/node_modules:ro
        entrypoint: ["bun", "run", "--watch", "./src/index.ts"]

    client:
        build:
            args:
                BUILD_ENV: development
        ports:
            - "5173:5173"
        volumes:
            - ./client/src:/app/client/src:ro
            - ./node_modules:/app/node_modules:ro
            - ./client/node_modules:/app/client/node_modules:ro
        entrypoint: ["bunx", "--bun", "vite", "--host"]
