services:
    server:
        build:
            dockerfile: server/Dockerfile.dev
        volumes:
            - .:/app:ro
            - root-node-modules:/app/node_modules
            - server-node-modules:/app/server/node_modules
            - client-node-modules:/app/client/node_modules
        entrypoint:
            [
                "bash",
                "-c",
                "cd /app && bun install && cd /app/server && bun run --watch ./src/index.ts",
            ]

    client:
        build:
            dockerfile: client/Dockerfile.dev
        ports:
            - "5173:5173"
        volumes:
            - .:/app:ro
            - root-node-modules:/app/node_modules
            - server-node-modules:/app/server/node_modules
            - client-node-modules:/app/client/node_modules
        entrypoint:
            ["bash", "-c", "cd /app && bun install && cd /app/client && bunx --bun vite --host"]

volumes:
    root-node-modules:
    server-node-modules:
    client-node-modules:
